/**
 * Reading helpers for the item-image variants generated by
 * `lib/image-pipeline.ts`. Frontend consumers use these to pick the
 * right URL for a given surface (list card, detail hero, etc.) with
 * graceful fallback to legacy fields (cover_url, poster_url, etc.).
 */

import { safeImageUrl } from "@/lib/image-url";

export type ImageSlot = "poster" | "backdrop";
export type ImageVariant = "s" | "m" | "l" | "xl";

interface SlotVariants {
  s?: string;
  m?: string;
  l?: string;
  xl?: string;
}

export interface ItemImagesShape {
  poster?:   SlotVariants;
  backdrop?: SlotVariants;
  og?:       string;
}

interface ItemLikeForImages {
  images?:       ItemImagesShape | null | unknown;
  poster_url?:   string | null;
  backdrop_url?: string | null;
  cover_url?:    string | null;
}

const VARIANT_FALLBACK: Record<ImageVariant, ImageVariant[]> = {
  s:  ["s",  "m",  "l",  "xl"],
  m:  ["m",  "s",  "l",  "xl"],
  l:  ["l",  "m",  "xl", "s"],
  xl: ["xl", "l",  "m",  "s"],
};

/**
 * Pick a URL for the given slot + preferred variant, falling back through
 * the variant ladder, then to the legacy column for that slot, then to
 * cover_url, then null.
 *
 * Example:
 *   itemImageUrl(item, "poster", "l")
 *     → tries images.poster.l, .m, .xl, .s
 *     → then poster_url
 *     → then cover_url
 *     → null if all empty
 */
export function itemImageUrl(
  item: ItemLikeForImages | null | undefined,
  slot: ImageSlot,
  preferredVariant: ImageVariant,
): string | null {
  if (!item) return null;

  const images = (item.images && typeof item.images === "object" && !Array.isArray(item.images))
    ? (item.images as ItemImagesShape)
    : null;
  const slotData = images?.[slot];

  if (slotData) {
    for (const v of VARIANT_FALLBACK[preferredVariant]) {
      const url = slotData[v];
      if (url) return safeImageUrl(url) ?? url;
    }
  }

  // Legacy column fallback
  if (slot === "poster" && item.poster_url) return safeImageUrl(item.poster_url);
  if (slot === "backdrop" && item.backdrop_url) return safeImageUrl(item.backdrop_url);
  if (item.cover_url) return safeImageUrl(item.cover_url);

  return null;
}

/**
 * Build a srcset string for Next.js <Image> from all available variants.
 * Returns undefined if no variants exist (caller should skip srcset prop).
 *
 * Example output:
 *   "https://.../poster-m.webp 480w, https://.../poster-l.webp 800w, https://.../poster-xl.webp 1600w"
 */
export function itemImageSrcSet(
  item: ItemLikeForImages | null | undefined,
  slot: ImageSlot,
): string | undefined {
  if (!item) return undefined;
  const images = (item.images && typeof item.images === "object" && !Array.isArray(item.images))
    ? (item.images as ItemImagesShape)
    : null;
  const slotData = images?.[slot];
  if (!slotData) return undefined;

  const widthPerVariant: Record<ImageVariant, Record<ImageSlot, number>> = {
    s:  { poster: 200,  backdrop: 320  },
    m:  { poster: 480,  backdrop: 640  },
    l:  { poster: 800,  backdrop: 1280 },
    xl: { poster: 1600, backdrop: 2048 },
  };

  const parts: string[] = [];
  for (const v of ["s", "m", "l", "xl"] as ImageVariant[]) {
    if (slotData[v]) parts.push(`${slotData[v]} ${widthPerVariant[v][slot]}w`);
  }
  return parts.length ? parts.join(", ") : undefined;
}

/** Return the OG / share image URL for an item, or null. */
export function itemOgUrl(item: ItemLikeForImages | null | undefined): string | null {
  if (!item) return null;
  const images = (item.images && typeof item.images === "object" && !Array.isArray(item.images))
    ? (item.images as ItemImagesShape)
    : null;
  if (images?.og) return safeImageUrl(images.og) ?? images.og;
  // Fall back to backdrop_url since OG is landscape-shaped
  if (item.backdrop_url) return safeImageUrl(item.backdrop_url);
  if (item.cover_url) return safeImageUrl(item.cover_url);
  return null;
}
